### ISSUE TITLE
Core clock requires /2 for hal-tick on stm32f429zi

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/cmsis-core-stm32f4#6]
As identified in https://github.com/ARMmbed/cmsis-core-stm32f4/pull/5, the core clock requires a /2.  This should not be the case.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-841

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1005
